[package]
name = "motion_detector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
log = "0.4.20"
mail-send = "0.4.4"
rppal = "0.16.1"
tokio = "1.35.1"
tokio-rustls = "0.25.0"